config:
  system:
    EnableMultithreading: true
    GenerationThreads: 6

  window:
    Height: 1080
    Width: 1920

  rendering:
    FOV: 65.0

    MaxBufferFaces: 2000
    TextureSize: 16
    TexturePack: "block_3" # To change a TP: Pack Textures and restart Game
    RenderDistance: 4
    TextureInverseOffset: 0.0085

    ChunkBorderColor:
      r: 1
      g: 0
      b: 0
      a: 0.75

    # Experimental
    ExpandTerrain: false

    shadows:
      MapSize: 4096
      BindMapToPlayerPos : true

  game:
    terrain:
      WorldWidth: 12
      ChunkSize: 16
      ChunkHeight: 40
      BlockSize: 1.0 # Better not touch
      YStretch: 5.0
      XStretch: 0.45
      MinHeight: 2
      
      # Higher = smaller biomes
      NoiseSizeMoist: 1.5
      NoiseSizeTemp: 1.5

    environment:
      FogAffectDistance: 37.0 # 28
      FogDensity: 0.2 # 0.3

      FogColor:
        r: 130
        g: 165
        b: 188

    movement:
      Gravitation: 0.50
      PlayerDrag: 0.3
      PlayerDragInAir: 0.035
      ControllInAir: 0.1

      SpeedSprint: 0.105
      SpeedWalk: 0.07
      SpeedCrouch: 0.04
      MaxFallSpeed: 0.35
      JumpStrenght: 0.13

      FOVwalking: 65.0
      FOVcrouching: 60.0
      FOVsprinting: 70.0

      BlockInteractionRange: 4.0

    gui:
      scale: 1.0