config:
  system:
    EnableMultithreading: true
    GenerationThreads: 4

  window:
    Height: 1080
    Width: 1920

  rendering:
    MaxBufferFaces: 2000
    TextureSize: 16
    RenderDistance: 3
    TextureInverseOffset: 1000

    # Experimental
    ExpandTerrain: false

  game:
    terrain:
      WorldWidth: 64
      ChunkSize: 16
      BlockSize: 1.0
      ChunkHeight: 15
      YStretch: 5.0
      XStretch: 0.5
      MinHeight: 10

    environment:
      FogAffectDistance: 80.0
      FogDensity: 0.35