config:
  system:
    EnableMultithreading: true
    GenerationThreads: 4

  window:
    Height: 1080
    Width: 1920

  rendering:
    MaxBufferFaces: 5000
    TextureSize: 16
    RenderDistance: 1
    TextureInverseOffset: 1000

  game:
    terrain:
      WorldWidth: 6
      ChunkSize: 16
      BlockSize: 1.0
      ChunkHeight: 10
      YStretch: 0.0
      XStretch: 1.0
      MinHeight: 10

    environment:
      FogAffectDistance: 80.0
      FogDensity: 0.2