config:
  system:
    EnableMultithreading: true
    GenerationThreads: 4

  window:
    Height: 1080
    Width: 1920

  rendering:
    MaxBufferFaces: 2000
    TextureSize: 16
    RenderDistance: 1
    TextureInverseOffset: 100

    ChunkBorderColor:
      r: 255
      g: 0
      b: 0

    # Experimental
    ExpandTerrain: false

  game:
    terrain:
      WorldWidth: 64
      ChunkSize: 16
      BlockSize: 1.0
      ChunkHeight: 30
      YStretch: 0.0
      XStretch: 0.75
      MinHeight: 5

    environment:
      FogAffectDistance: 40.0
      FogDensity: 0.4

      FogColor:
        r: 130
        g: 165
        b: 188