config:
  system:
    EnableMultithreading: true
    GenerationThreads: 4

  window:
    Height: 1080
    Width: 1920

  rendering:
    MaxBufferFaces: 5000
    TextureSize: 16
    RenderDistance: 3
    TextureInverseOffset: 1000
    ExpandTerrain: false

  game:
    terrain:
      WorldWidth: 64
      ChunkSize: 16
      BlockSize: 1.0
      ChunkHeight: 20
      YStretch: 10.0
      XStretch: 0.5
      MinHeight: 10

    environment:
      FogAffectDistance: 30.0
      FogDensity: 0.47