config:
  system:
    EnableMultithreading: true
    GenerationThreads: 6

  window:
    Height: 1080
    Width: 1920

  rendering:
    FOV: 65.0

    MaxBufferFaces: 2000
    TextureSize: 16
    RenderDistance: 6
    TextureInverseOffset: 100

    ChunkBorderColor:
      r: 1
      g: 0
      b: 0
      a: 0.75

    # Experimental
    ExpandTerrain: false

  game:
    terrain:
      WorldWidth: 32
      ChunkSize: 16
      ChunkHeight: 35
      BlockSize: 1.0 # Better not touch
      YStretch: 20.0
      XStretch: 0.35
      MinHeight: 2
      
      # Higher = smaller biomes
      NoiseSizeMoist: 0.8
      NoiseSizeTemp: 0.8

    environment:
      FogAffectDistance: 280.0 # 28
      FogDensity: 0.3 # 0.3

      FogColor:
        r: 130
        g: 165
        b: 188

    movement:
      Gravitation: 0.50
      PlayerDrag: 0.3
      PlayerDragInAir: 0.035
      ControllInAir: 0.1

      SpeedSprint: 0.105
      SpeedWalk: 0.07
      SpeedCrouch: 0.04
      MaxFallSpeed: 0.35
      JumpStrenght: 0.13

      FOVwalking: 65.0
      FOVcrouching: 60.0
      FOVsprinting: 70.0

      BlockInteractionRange: 4.0

    gui:
      scale: 1.0