config:
  system:
    EnableMultithreading: true
    GenerationThreads: 4

  window:
    Height: 1080
    Width: 1920

  rendering:
    FOV: 65.0

    MaxBufferFaces: 2000
    TextureSize: 16
    RenderDistance: 1
    TextureInverseOffset: 100

    ChunkBorderColor:
      r: 1
      g: 0
      b: 0
      a: 1

    # Experimental
    ExpandTerrain: false

  game:
    terrain:
      WorldWidth: 64
      ChunkSize: 16
      BlockSize: 1.0
      ChunkHeight: 8
      YStretch: 1.0
      XStretch: 0.7
      MinHeight: 3

    environment:
      FogAffectDistance: 20.0 # 15
      FogDensity: 0.5 # 0.5

      FogColor:
        r: 130
        g: 165
        b: 188

    movement:
      Gravitation: 0.50
      PlayerDrag: 0.3
      PlayerDragInAir: 0.035
      ControllInAir: 0.1

      SpeedSprint: 0.105
      SpeedWalk: 0.07
      SpeedCrouch: 0.04
      MaxFallSpeed: 0.35
      JumpStrenght: 0.13

      FOVwalking: 65.0
      FOVcrouching: 60.0
      FOVsprinting: 70.0

      BlockInteractionRange: 4.0

    gui:
      scale: 1.0